version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 15
    revive:
      severity: warning
      rules:
        - name: exported
          disabled: false
        - name: package-comments
          disabled: false

formatters:
  enable:
    - gofmt
    - goimports
